import { createServerFn } from "@tanstack/react-start";

export type ProductVariant = {
  id: string;
  label: string;
  price: number;
  stock: number;
  cost: number;
  lowStock: number | null;
  availableForSale: boolean;
  sku: string;
  image?: string | null;
};

export type CatalogProduct = {
  id: string; // representative variant_id
  itemId: string;
  name: string;
  price: number;
  image: string | null;
  images: string[];
  stock: number;
  description: string;
  /** true when the description was generated by the app (no Loyverse description). */
  generatedDescription: boolean;
  sku: string;
  categoryId: string | null;
  categoryName: string;
  /** Name of the variation axis, e.g. "Tamanho", "Cor". Empty when single. */
  variantAxis: string;
  variants: ProductVariant[];
  /** Selo comercial (Destaque/Oferta/Mais vendido), calculado no servidor. */
  badge?: { label: string; tone: "featured" | "top" | "offer" } | null;
};

export type Category = {
  id: string;
  name: string;
};

export type Catalog = {
  products: CatalogProduct[];
  categories: Category[];
  /** Image of the Loyverse item named "LOGO DA LOJA" (never sold). */
  storeLogo: string | null;
};

/** True for the reserved item that holds the store brand image. */
export function isStoreLogoName(name: string): boolean {
  return (
    name
      .toLowerCase()
      .normalize("NFD")
      .replace(/\p{Diacritic}/gu, "")
      .replace(/\s+/g, " ")
      .trim() === "logo da loja"
  );
}


type LoyverseVariant = {
  variant_id: string;
  sku?: string | null;
  option1_value?: string | null;
  option2_value?: string | null;
  option3_value?: string | null;
  default_price?: number | null;
  cost?: number | null;
  purchase_cost?: number | null;
  stores?: Array<{
    price?: number | null;
    available_for_sale?: boolean | null;
    low_stock?: number | null;
  }>;
};

type LoyverseItem = {
  id: string;
  item_name: string;
  description?: string | null;
  category_id?: string | null;
  image_url?: string | null;
  track_stock?: boolean;
  option1_name?: string | null;
  option2_name?: string | null;
  option3_name?: string | null;
  variants?: LoyverseVariant[];
};

type InventoryLevel = {
  variant_id: string;
  in_stock?: number | null;
};

function stripHtml(s: string): string {
  return s
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]*>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .trim();
}

function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[()\[\]{}<>]/g, " ")
    .replace(/[-_/]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Matches size/measure tokens like 41, 41/42, P, M, GG, 500ml, 1,5l, 30cm. */
const SIZE_TOKEN =
  /^(?:\d{1,3}(?:[/-]\d{1,3})?|pp|p|m|g|gg|xg|xgg|xs|s|l|xl|xxl|un|\d+(?:[.,]\d+)?\s?(?:ml|l|kg|g|mg|cm|mm|m|un|pcs))$/i;

/** Matches measures like 3,5X25, 4.8x50mm, 6X40. */
const MEASURE_TOKEN = /^\d+(?:[.,]\d+)?\s*[xX×]\s*\d+(?:[.,]\d+)?(?:mm|cm|m)?$/;

const COLOR_TOKEN =
  /^(?:preto|preta|branco|branca|azul|vermelho|vermelha|verde|amarelo|amarela|rosa|cinza|marrom|bege|roxo|roxa|laranja|dourado|prata|nude|vinho)$/i;

const VARIATION_PREFIX = /^(tam|tamanho|medida|nº|n|num|numero|número|cor|modelo|capacidade|vol|voltage)$/i;

function isVariationTail(s: string): boolean {
  const value = s.trim();
  if (!value) return false;
  if (SIZE_TOKEN.test(value)) return true;
  if (MEASURE_TOKEN.test(value)) return true;
  if (COLOR_TOKEN.test(value)) return true;

  const compact = value.replace(/[^a-z0-9]/gi, "").toLowerCase();
  if (/^(\d+|\d+[a-z]+)$/i.test(value)) return true;
  if (/^(?:[a-z]+\d+[a-z]*)$/i.test(value) && compact.length > 1) return true;
  return false;
}

/** Axis name inferred from a variation label. */
function axisForLabel(label: string): string {
  if (MEASURE_TOKEN.test(label)) return "Medida";
  if (SIZE_TOKEN.test(label)) return "Tamanho";
  if (COLOR_TOKEN.test(label)) return "Cor";
  if (/^[\d.,]+\s*[xX×]\s*[\d.,]+/.test(label)) return "Medida";
  return "Variação";
}

/** Splits "Chinelo 41/42" or "Parafuso Chip (3,5X25)" into base + label. */
function splitVariation(name: string): { base: string; label: string; axis: string } {
  const cleaned = name.replace(/\s+/g, " ").trim();
  if (!cleaned) return { base: "", label: "", axis: "" };

  // Trailing parentheses always mark a variation: "Parafuso Chip (3,5X25)".
  const paren = cleaned.match(/^(.+?)\s*\(([^()]+)\)$/);
  if (paren && paren[1].trim() && paren[2].trim()) {
    const label = paren[2].trim();
    return { base: paren[1].trim(), label, axis: axisForLabel(label) };
  }

  const words = cleaned.split(/\s+/);
  if (words.length < 2) return { base: cleaned, label: "", axis: "" };


  const last = words[words.length - 1].replace(/[.,;]+$/g, "");
  const beforeLast = words[words.length - 2];

  if (
    words.length >= 3 &&
    VARIATION_PREFIX.test(beforeLast) &&
    isVariationTail(last)
  ) {
    return {
      base: words.slice(0, -2).join(" "),
      label: last,
      axis: /^(cor|modelo|capacidade|vol|voltage)$/i.test(beforeLast) ? "Variação" : "Tamanho",
    };
  }

  if (isVariationTail(last)) {
    return {
      base: words.slice(0, -1).join(" "),
      label: last,
      axis: axisForLabel(last),
    };
  }

  const compact = cleaned.replace(/\s*\([^)]*\)\s*$/g, "").trim();
  const compactWords = compact.split(/\s+/);
  if (compactWords.length >= 2) {
    const compactLast = compactWords[compactWords.length - 1];
    if (isVariationTail(compactLast)) {
      return {
        base: compactWords.slice(0, -1).join(" "),
        label: compactLast,
        axis: SIZE_TOKEN.test(compactLast) ? "Tamanho" : COLOR_TOKEN.test(compactLast) ? "Cor" : "Variação",
      };
    }
  }

  return { base: cleaned, label: "", axis: "" };
}

function variantLabelFromOptions(v: LoyverseVariant): string {
  return [v.option1_value, v.option2_value, v.option3_value]
    .filter((x): x is string => Boolean(x && x.trim()))
    .join(" / ");
}

function optionAxis(item: LoyverseItem): string {
  return (
    [item.option1_name, item.option2_name, item.option3_name]
      .filter((x): x is string => Boolean(x && x.trim()))
      .join(" / ") || "Variação"
  );
}

/** Builds a detailed description when Loyverse has none. */
function buildDescription(
  name: string,
  categoryName: string,
  variants: ProductVariant[],
  axis: string,
  price: number,
): string {
  const parts: string[] = [];
  parts.push(
    `${name} — produto da linha ${categoryName.toLowerCase()} disponível na SPERB.`,
  );
  if (variants.length > 1 && axis) {
    parts.push(
      `Disponível em ${variants.length} opções de ${axis.toLowerCase()}: ${variants
        .map((v) => v.label)
        .filter(Boolean)
        .join(", ")}. Escolha a opção desejada antes de adicionar ao carrinho.`,
    );
  }
  const total = variants.reduce(
    (s, v) => s + (Number.isFinite(v.stock) ? v.stock : 0),
    0,
  );
  if (Number.isFinite(total) && total > 0) {
    parts.push(
      total <= 5
        ? `Últimas ${total} unidades disponíveis em estoque.`
        : `Temos ${total} unidades disponíveis em estoque.`,
    );
  }
  parts.push(
    `Valor a partir de R$ ${price.toFixed(2).replace(".", ",")}. Estoque e preço sincronizados em tempo real com a nossa loja física.`,
  );
  parts.push(
    `Ficou com dúvida sobre medidas, cor ou uso do produto? Fale com a gente pelo WhatsApp antes de finalizar o pedido — respondemos rapidinho.`,
  );
  return parts.join("\n\n");
}

/** Tempo limite de cada chamada ao Loyverse (a resposta nunca fica pendurada). */
const LOYVERSE_TIMEOUT_MS = 8_000;

async function loyverseGet<T>(
  path: string,
  token: string,
  extra?: Record<string, string>,
): Promise<T[]> {
  const out: T[] = [];
  let cursor: string | undefined;
  do {
    const url = new URL(`https://api.loyverse.com/v1.0/${path}`);
    url.searchParams.set("limit", "250");
    for (const [k, v] of Object.entries(extra ?? {})) url.searchParams.set(k, v);
    if (cursor) url.searchParams.set("cursor", cursor);

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), LOYVERSE_TIMEOUT_MS);
    let res: Response;
    try {
      res = await fetch(url.toString(), {
        headers: { Authorization: `Bearer ${token}` },
        signal: controller.signal,
      });
    } catch (err) {
      if (controller.signal.aborted) {
        throw new Error(`Loyverse ${path}: tempo limite de ${LOYVERSE_TIMEOUT_MS}ms`);
      }
      throw err;
    } finally {
      clearTimeout(timer);
    }

    if (!res.ok) throw new Error(`Loyverse ${path} ${res.status}: ${await res.text()}`);
    const data = (await res.json()) as Record<string, unknown>;
    const key = Object.keys(data).find((k) => Array.isArray(data[k]));
    if (key) out.push(...((data[key] as T[]) ?? []));
    cursor = (data.cursor as string | undefined) || undefined;
  } while (cursor);
  return out;
}

type Draft = {
  key: string;
  name: string;
  itemId: string;
  image: string | null;
  images: string[];
  description: string;
  categoryId: string | null;
  categoryName: string;
  axis: string;
  variants: ProductVariant[];
};

async function buildCatalog(token: string): Promise<Catalog> {
  const [items, rawCategories] = await Promise.all([
    loyverseGet<LoyverseItem>("items", token),
    loyverseGet<{ id: string; name: string; deleted_at?: string | null }>(
      "categories",
      token,
    ).catch(() => []),
  ]);

  let inventory: InventoryLevel[] = [];
  try {
    inventory = await loyverseGet<InventoryLevel>("inventory", token);
  } catch {
    inventory = [];
  }

  const stockByVariant = new Map<string, number>();
  for (const lvl of inventory) {
    const prev = stockByVariant.get(lvl.variant_id) ?? 0;
    stockByVariant.set(lvl.variant_id, prev + (Number(lvl.in_stock) || 0));
  }

  const categoryNames = new Map<string, string>();
  for (const c of rawCategories) {
    if (c.deleted_at) continue;
    categoryNames.set(c.id, c.name);
  }

  const drafts = new Map<string, Draft>();
  let storeLogo: string | null = null;

  for (const it of items) {
    // The item named "LOGO DA LOJA" is the store brand image, never a product.
    if (isStoreLogoName(it.item_name)) {
      if (it.image_url) storeLogo = it.image_url;
      continue;
    }
    const itemVariants = it.variants ?? [];
    if (itemVariants.length === 0) continue;


    const categoryName =
      (it.category_id && categoryNames.get(it.category_id)) || "Outros";
    const tracked = it.track_stock !== false;
    const hasOptions = itemVariants.some((v) =>
      Boolean(v.option1_value || v.option2_value || v.option3_value),
    );

    const split = splitVariation(it.item_name);
    // Items with real Loyverse options keep their own name; items named
    // "Chinelo 41/42" are merged with siblings sharing the same base name.
    const useNameSplit = !hasOptions && Boolean(split.label);
    const baseName = useNameSplit ? split.base : it.item_name.trim();
    const key = `${normalize(baseName)}::${it.category_id ?? "none"}`;

    const variants: ProductVariant[] = itemVariants.map((v) => {
      const store = v.stores?.find((s) =>
        typeof s.price === "number" ||
        typeof s.available_for_sale === "boolean" ||
        typeof s.low_stock === "number",
      );
      const rawPrice = store?.price ?? v.default_price ?? 0;
      const stockNum = stockByVariant.get(v.variant_id);
      const cost = Number(v.cost ?? v.purchase_cost ?? 0) || 0;
      const lowStock =
        typeof store?.low_stock === "number" ? Math.max(0, store.low_stock) : null;
      const availableForSale = store?.available_for_sale !== false;
      return {
        id: v.variant_id,
        label: hasOptions
          ? variantLabelFromOptions(v)
          : useNameSplit
            ? split.label
            : "",
        price: Number(rawPrice) || 0,
        cost,
        lowStock,
        availableForSale,
        stock: tracked
          ? Math.max(0, Math.floor(stockNum ?? 0))
          : Number.POSITIVE_INFINITY,
        sku: v.sku ?? "",
        image: it.image_url ?? null,
      };
    });

    const axis = hasOptions ? optionAxis(it) : useNameSplit ? split.axis : "";
    const existing = drafts.get(key);
    if (existing) {
      existing.variants.push(...variants);
      if (it.image_url) {
        if (!existing.image) existing.image = it.image_url;
        if (!existing.images.includes(it.image_url)) existing.images.push(it.image_url);
      }
      if (!existing.description && it.description) {
        existing.description = stripHtml(it.description);
      }
      if (!existing.axis && axis) existing.axis = axis;
    } else {
      drafts.set(key, {
        key,
        name: baseName,
        itemId: it.id,
        image: it.image_url ?? null,
        images: it.image_url ? [it.image_url] : [],
        description: it.description ? stripHtml(it.description) : "",
        categoryId: it.category_id ?? null,
        categoryName,
        axis,
        variants,
      });
    }
  }

  const products: CatalogProduct[] = [];
  for (const d of drafts.values()) {
    // Dedupe + stable ordering of variants (numeric sizes first, ascending).
    const seen = new Set<string>();
    const variants = d.variants
      .filter((v) => (seen.has(v.id) ? false : (seen.add(v.id), true)))
      .sort((a, b) => {
        const na = parseFloat(a.label.replace(",", "."));
        const nb = parseFloat(b.label.replace(",", "."));
        if (!Number.isNaN(na) && !Number.isNaN(nb)) return na - nb;
        return a.label.localeCompare(b.label, "pt-BR");
      });

    const inStock = variants.filter((v) => v.stock > 0);
    const priceSource = inStock.length > 0 ? inStock : variants;
    const price = Math.min(...priceSource.map((v) => v.price));
    const stock = variants.reduce(
      (s, v) => s + (Number.isFinite(v.stock) ? v.stock : Number.POSITIVE_INFINITY),
      0,
    );
    const representative = inStock[0] ?? variants[0];
    const axis = variants.length > 1 ? d.axis || "Variação" : "";
    const generated = !d.description;

    products.push({
      id: representative.id,
      itemId: d.itemId,
      name: d.name,
      price,
      image: d.image,
      images: d.images,
      stock,

      description: generated
        ? buildDescription(d.name, d.categoryName, variants, axis, price)
        : d.description,
      generatedDescription: generated,
      sku: representative.sku,
      categoryId: d.categoryId,
      categoryName: d.categoryName,
      variantAxis: axis,
      variants,
    });
  }

  products.sort((a, b) => a.name.localeCompare(b.name, "pt-BR"));

  const usedIds = new Set(products.map((p) => p.categoryId).filter(Boolean) as string[]);
  const categories: Category[] = [...usedIds]
    .map((id) => ({ id, name: categoryNames.get(id) ?? "Outros" }))
    .sort((a, b) => a.name.localeCompare(b.name, "pt-BR"));
  if (products.some((p) => !p.categoryId)) {
    categories.push({ id: "sem-categoria", name: "Outros" });
  }

  return { products, categories, storeLogo };
}

/** Janela de cache em memória do servidor (evita estourar a API do Loyverse). */
const FRESH_MS = 5_000;
/** Até este limite a cópia oficial do banco é aceita sem consultar o Loyverse. */
const SNAPSHOT_MAX_AGE_MS = 3 * 60_000;

let memoryCatalog: { at: number; catalog: Catalog } | null = null;
let refreshing: Promise<Catalog> | null = null;

/** Níveis de estoque por variação (leitura leve, usada pela conferência rápida). */
export async function fetchInventoryLevels(
  token: string,
): Promise<Map<string, number>> {
  const levels = await loyverseGet<InventoryLevel>("inventory", token);
  const byVariant = new Map<string, number>();
  for (const lvl of levels) {
    const prev = byVariant.get(lvl.variant_id) ?? 0;
    byVariant.set(lvl.variant_id, prev + (Number(lvl.in_stock) || 0));
  }
  for (const [id, value] of byVariant) {
    byVariant.set(id, Math.max(0, Math.floor(value)));
  }
  return byVariant;
}

/** Reconstrói o catálogo direto do Loyverse e atualiza a cópia oficial. */
export async function syncCatalogFromLoyverse(): Promise<Catalog> {
  if (refreshing) return refreshing;
  refreshing = (async () => {
    const token = process.env.LOYVERSE_TOKEN;
    if (!token) throw new Error("LOYVERSE_TOKEN ausente");
    const catalog = await buildCatalog(token);
    memoryCatalog = { at: Date.now(), catalog };
    try {
      const { writeCatalogSnapshot } = await import("@/lib/catalog-snapshot.server");
      await writeCatalogSnapshot(catalog, true);
    } catch (err) {
      console.error("[Catalog] não foi possível gravar a cópia oficial:", err);
    }
    return catalog;
  })();
  try {
    return await refreshing;
  } finally {
    refreshing = null;
  }
}

/**
 * O catálogo vem do Loyverse, mas quem responde o app é a cópia oficial no
 * banco: ela é a mesma para todos os aparelhos e é atualizada pelo servidor
 * (aviso do Loyverse + conferência de 5 em 5 segundos).
 */
async function getCatalog(): Promise<Catalog> {
  const age = memoryCatalog ? Date.now() - memoryCatalog.at : Infinity;
  if (memoryCatalog && age < FRESH_MS) {
    return memoryCatalog.catalog;
  }

  try {
    const { readCatalogSnapshot } = await import("@/lib/catalog-snapshot.server");
    const snapshot = await readCatalogSnapshot();
    if (snapshot && Date.now() - snapshot.updatedAt < SNAPSHOT_MAX_AGE_MS) {
      memoryCatalog = { at: Date.now(), catalog: snapshot.catalog };
      return snapshot.catalog;
    }
  } catch (err) {
    console.error("[Catalog] cópia oficial indisponível:", err);
  }

  try {
    return await syncCatalogFromLoyverse();
  } catch (err) {
    if (memoryCatalog) {
      console.error("[Catalog] falha no Loyverse, usando cópia recente:", err);
      return memoryCatalog.catalog;
    }
    throw err;
  }
}

export const fetchCatalog = createServerFn({ method: "GET" }).handler(
  async (): Promise<Catalog> => {
    // A vitrine sai do servidor JÁ na ordem final (destaques no início,
    // resto sorteado a cada abertura) — a primeira tela já é a certa.
    const { orderCatalog } = await import("@/lib/merch-order.server");
    return orderCatalog(await getCatalog());
  },
);

/** Só os produtos que mudaram (atualização cirúrgica da vitrine aberta). */
export const fetchProductsByIds = createServerFn({ method: "GET" })
  .inputValidator((data: { ids: string[] }) => ({
    ids: Array.isArray(data?.ids) ? data.ids.filter(Boolean).slice(0, 200) : [],
  }))
  .handler(async ({ data }): Promise<CatalogProduct[]> => {
    if (data.ids.length === 0) return [];
    const wanted = new Set(data.ids);
    const { products } = await getCatalog();
    return products.filter((p) => wanted.has(p.id));
  });




export const fetchProducts = createServerFn({ method: "GET" }).handler(
  async (): Promise<CatalogProduct[]> => (await getCatalog()).products,
);

export const fetchProduct = createServerFn({ method: "GET" })
  .inputValidator((data: { id: string }) => {
    if (!data || typeof data.id !== "string" || !data.id) {
      throw new Error("Produto inválido");
    }
    return { id: data.id };
  })
  .handler(async ({ data }): Promise<CatalogProduct | null> => {
    const { products } = await getCatalog();
    return (
      products.find((p) => p.id === data.id) ??
      products.find((p) => p.variants.some((v) => v.id === data.id)) ??
      null
    );
  });


/**
 * Estoque real das variações pedidas (usado pela reserva atômica).
 * Produtos sem controle de estoque no Loyverse voltam com um número grande.
 */
export async function fetchLiveStock(
  ids: string[],
): Promise<Array<{ id: string; productKey: string; name: string; stock: number }>> {
  const wanted = new Set(ids.filter(Boolean));
  if (wanted.size === 0) return [];
  const { products } = await getCatalog();
  const out: Array<{ id: string; productKey: string; name: string; stock: number }> = [];
  const push = (id: string, name: string, stock: number) => {
    if (!wanted.has(id)) return;
    out.push({
      id,
      productKey: id,
      name,
      stock: Number.isFinite(stock) ? stock : 1_000_000,
    });
  };
  for (const p of products) {
    push(p.id, p.name, p.stock);
    for (const v of p.variants) push(v.id, `${p.name} ${v.label}`.trim(), v.stock);
  }
  return out;
}
