import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useServerFn } from "@tanstack/react-start";
import { ArrowUp, ImagePlus, Loader2, X, Sparkles, Trash2, AlertTriangle } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { assistantChat } from "@/lib/assistant-chat.functions";
import type { ChatState, ChatProduct, Mode } from "@/lib/assistant-chat.types";

const MAX_IMAGES = 10;
const ALLOWED = ["image/jpeg", "image/png", "image/webp"];
const MAX_SIDE = 1600;
type Prepared = { mime: string; data: string };
type Crop = { x: number; y: number; width: number; height: number };

function toBase64(file: File): Promise<string> { return new Promise((resolve, reject) => { const r = new FileReader(); r.onerror=()=>reject(new Error("Não consegui ler o arquivo.")); r.onload=()=>{const s=String(r.result??"");resolve(s.slice(s.indexOf(",")+1));}; r.readAsDataURL(file); }); }
async function shrink(file: File): Promise<Prepared> {
  try { const b=await createImageBitmap(file); const scale=Math.min(1,MAX_SIDE/Math.max(b.width,b.height)); if(scale>=1&&file.size<=1200000){b.close();return {mime:file.type,data:await toBase64(file)}} const c=document.createElement("canvas");c.width=Math.round(b.width*scale);c.height=Math.round(b.height*scale);const x=c.getContext("2d");if(!x)throw new Error("sem canvas");x.drawImage(b,0,0,c.width,c.height);b.close();const u=c.toDataURL("image/jpeg",.85);return {mime:"image/jpeg",data:u.slice(u.indexOf(",")+1)}; } catch { return {mime:file.type,data:await toBase64(file)}; }
}
async function hashText(value:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
async function cropImage(source:Prepared,crop?:Crop):Promise<Prepared>{
  if(!crop)throw new Error("A IA não conseguiu separar o produto da tela com segurança.");
  const bytes=Uint8Array.from(atob(source.data),c=>c.charCodeAt(0));const b=await createImageBitmap(new Blob([bytes],{type:source.mime}));
  const x=Math.max(0,Math.floor(crop.x*b.width)),y=Math.max(0,Math.floor(crop.y*b.height));const w=Math.min(b.width-x,Math.floor(crop.width*b.width)),h=Math.min(b.height-y,Math.floor(crop.height*b.height));
  if(w<8||h<8){b.close();throw new Error("Recorte do produto muito pequeno.");}
  const side=Math.min(Math.max(w,h),Math.min(b.width,b.height));const cx=Math.min(Math.max(0,Math.round(x+w/2-side/2)),b.width-side);const cy=Math.min(Math.max(0,Math.round(y+h/2-side/2)),b.height-side);
  const size=Math.min(1200,Math.max(256,side));const c=document.createElement("canvas");c.width=size;c.height=size;const ctx=c.getContext("2d");if(!ctx){b.close();throw new Error("Não consegui preparar a foto.");}ctx.drawImage(b,cx,cy,side,side,0,0,size,size);b.close();const u=c.toDataURL("image/jpeg",.9);return {mime:"image/jpeg",data:u.slice(u.indexOf(",")+1)};
}

export function AssistantPanel({onClose}:{color:string;onClose:()=>void}){
 const request=useServerFn(assistantChat);
 async function call(args:Parameters<typeof request>[0]):Promise<ChatState>{const result=await request(args);if("busy" in result)throw new Error(result.message);return result;}
 const generation=useRef(0),active=useRef(0),prepared=useRef(new Map<string,Prepared>()),seen=useRef(new Set<string>()),latest=useRef<ChatState|null>(null);
 const [chat,setChat]=useState<ChatState|null>(null),[text,setText]=useState(""),[files,setFiles]=useState<File[]>([]),[mode,setMode]=useState<Mode>("store"),[busy,setBusy]=useState(false),[stage,setStage]=useState(""),[error,setError]=useState(""),[mounted,setMounted]=useState(false),[resetting,setResetting]=useState(false),[attentionOpen,setAttentionOpen]=useState(false),[draftEdits,setDraftEdits]=useState<Record<string,{name?:string;qty?:number;cost?:number;price?:number}>>({});
 const input=useRef<HTMLInputElement>(null),composer=useRef<HTMLTextAreaElement>(null),bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{setMounted(true);void call({data:{action:"state"}}).then(v=>{latest.current=v;setChat(v);composer.current?.focus();}).catch(e=>setError(e instanceof Error?e.message:String(e)));},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[chat?.messages.length,stage]);
 async function resetChat(clear=false){if(!latest.current||resetting)return;if(clear&&!window.confirm("Excluir todo o histórico? Produtos, preços e estoque já salvos serão preservados."))return;generation.current++;setResetting(true);try{const v=await call({data:{action:clear?"clear":"cancel",id:latest.current.id}});latest.current=v;setChat(v);prepared.current.clear();seen.current.clear();setFiles([]);setText("");setError("");setStage("");}catch(e){setError(e instanceof Error?e.message:"Não foi possível reiniciar.")}finally{setResetting(false)}}
 async function send(){if(resetting||!chat||(!text.trim()&&!files.length))return;if(/^(?:por favor[, ]*)?(?:cancelar|cancela|cancele|parar|pare)(?: tudo| isso| o processamento)?[.!]?$/i.test(text.trim())){await resetChat();return;}const version=generation.current,instruction=text,batch=files;let current=latest.current??chat;setText("");setFiles([]);active.current++;setBusy(true);setError("");try{
   let next=0;const worker=async()=>{while(next<batch.length){if(version!==generation.current)throw new Error("Operação cancelada.");const i=next++,file=batch[i];if(!file)continue;setStage(`Imagem ${i+1} de ${batch.length}: lendo…`);try{const image=await shrink(file),sourceHash=await hashText(image.data);if(seen.current.has(sourceHash))continue;seen.current.add(sourceHash);prepared.current.set(sourceHash,image);const session=await supabase.auth.getSession(),token=session.data.session?.access_token;if(!token)throw new Error("Entre novamente como administrador.");const response=await fetch("/api/assistant/analyze",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({id:current.id,mode,image:{name:file.name,...image}})});if(!response.ok||!response.body)throw new Error(`Falha na leitura (${response.status}).`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});let end;while((end=buffer.indexOf("\n"))>=0){const event=JSON.parse(buffer.slice(0,end));buffer=buffer.slice(end+1);if(event.result){current=event.result;latest.current=current;setChat(current)}if(event.error)throw new Error(event.error)}}}catch(e){setError(`${file.name}: precisa de conferência — ${e instanceof Error?e.message:"Falha na imagem"}`)}}};await Promise.all(Array.from({length:Math.min(3,batch.length)},()=>worker()));
   current=await call({data:{action:"state",id:current.id}});latest.current=current;setChat(current);if(instruction.trim()){setStage("Entendendo sua mensagem…");current=await call({data:{action:"text",id:current.id,text:instruction}});latest.current=current;setChat(current)}
  }catch(e){if(version===generation.current)setError(e instanceof Error?e.message:"Não foi possível responder. Envie novamente.")}finally{if(version===generation.current)setStage("");active.current--;setBusy(active.current>0);composer.current?.focus()}}
 function updateDraft(p:ChatProduct,changes:{name?:string;qty?:number;cost?:number;price?:number}){setDraftEdits(old=>({...old,[p.id]:{...(old[p.id]??{}),...changes}}));}
 async function saveAll(){if(!chat)return;active.current++;setBusy(true);setError("");setStage("Preparando as imagens e salvando os produtos…");try{const items=[] as Array<{productId:string;name?:string;qty?:number;cost?:number;price?:number;image?:Prepared}>;for(const p of chat.pendingProducts){const e=draftEdits[p.id]??{};const price=Number(e.price??p.draft.manualPrice??p.result?.salePrice??0);if(p.status==="review"||price<=0||!p.draft.crop)continue;const source=prepared.current.get(String(p.draft.sourceHash??""));if(!source){setError(`${p.draft.name}: a foto desta sessão não está disponível. Reenvie a foto para este produto.`);continue}const image=await cropImage(source,p.draft.crop as Crop);items.push({productId:p.id,name:e.name,qty:e.qty,cost:e.cost,price,image});}if(!items.length)throw new Error("Defina o preço de venda e corrija as pendências antes de salvar.");let v=chat;for(let i=0;i<items.length;i+=10){v=await call({data:{action:"saveAll",id:chat.id,items:items.slice(i,i+10)}});latest.current=v;setChat(v)}setDraftEdits({});if(!v.pendingProducts.length)setAttentionOpen(false)}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar os produtos.")}finally{setStage("");active.current--;setBusy(active.current>0)}}
 const pending=chat?.pendingProducts??[];const ready=pending.filter(p=>p.status!=="review"&&Number(draftEdits[p.id]?.price??p.draft.manualPrice??p.result?.salePrice??0)>0&&p.draft.crop);const attentionCount=pending.length;
 if(!mounted)return null;
 return createPortal(<section role="dialog" aria-modal="true" aria-label="Assistente SPERB" className="fixed inset-0 z-[100] flex h-dvh flex-col bg-background text-foreground">
  <header className="flex shrink-0 items-center justify-between border-b bg-background/95 px-4 py-3 backdrop-blur"><div className="flex min-w-0 items-center gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-2xl bg-primary/10"><Sparkles className="size-5 text-primary"/></div><div className="min-w-0"><h1 className="truncate text-base font-bold sm:text-lg">Assistente SPERB</h1><p className="text-xs text-muted-foreground">Administração da loja · memória de 30 dias</p></div></div><div className="flex shrink-0 items-center gap-1"><Button variant="ghost" size="sm" title="Produtos que precisam da sua atenção" aria-label="Produtos que precisam da sua atenção" disabled={!chat||resetting} onClick={()=>setAttentionOpen(true)} className="relative gap-1 px-2"><AlertTriangle className="size-4 text-amber-600"/><span className="hidden sm:inline text-xs">Atenção</span>{attentionCount>0&&<span className="absolute -right-0.5 -top-0.5 flex min-w-4 h-4 items-center justify-center rounded-full bg-amber-500 px-1 text-[10px] font-bold text-white">{attentionCount>9?"9+":attentionCount}</span>}</Button><Button variant="ghost" size="icon" title="Excluir todo o chat" aria-label="Excluir todo o chat" disabled={!chat||resetting} onClick={()=>void resetChat(true)}><Trash2 className="size-5"/></Button><Button variant="ghost" size="icon" title="Fechar Assistente" aria-label="Fechar Assistente" disabled={busy} onClick={onClose}><X className="size-5"/></Button></div></header>
  <div className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-3xl space-y-5 px-4 py-6">{!chat&&!error&&<Loader2 className="animate-spin"/>}{chat?.messages.length===0&&<div className="py-16 text-center"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-primary/10"><Sparkles className="size-7 text-primary"/></div><h2 className="mt-4 text-lg font-semibold">O que você quer fazer?</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">Dê uma ordem para a administração da SPERB ou envie fotos das suas compras. Eu preparo os produtos e só cadastro depois da sua confirmação.</p></div>}{chat?.messages.map(m=><article key={m.id} className={m.role==="user"?"ml-auto max-w-[90%] rounded-2xl bg-muted p-3":"max-w-full py-1"}><p className="mb-1 text-xs font-bold text-muted-foreground">{m.role==="user"?"Você":"Assistente SPERB"}</p><div className="break-words text-base leading-relaxed"><ReactMarkdown>{m.content}</ReactMarkdown></div></article>)}{stage&&<p role="status" className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>{stage}</p>}{error&&<p role="alert" className="break-words rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div ref={bottom}/></div></div>
  <footer className="shrink-0 border-t bg-background px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-3"><div className="mx-auto max-w-3xl space-y-2"><div className="flex gap-2">{([["store","🏪 Produto da loja"],["order","📦 Produto por encomenda"]] as const).map(([v,l])=><Button key={v} variant={mode===v?"default":"outline"} onClick={()=>setMode(v)} className="h-auto min-h-10 flex-1 whitespace-normal px-2 text-xs sm:flex-none sm:text-sm">{l}</Button>)}</div>{!!files.length&&<div className="flex flex-wrap gap-2">{files.map((f,i)=><Button key={i} size="sm" variant="secondary" onClick={()=>setFiles(old=>old.filter((_,n)=>n!==i))}>{f.name.slice(0,26)} <X className="size-3"/></Button>)}</div>}<form onSubmit={e=>{e.preventDefault();void send()}} className="flex items-end gap-2 rounded-xl border bg-card p-2"><input ref={input} type="file" multiple accept={ALLOWED.join(",")} className="hidden" onChange={e=>{const next=[...files,...Array.from(e.target.files??[])];e.target.value="";if(next.length>MAX_IMAGES){setError("Envie até 10 imagens por lote.");return}if(next.some(f=>!ALLOWED.includes(f.type)||f.size>8*1024*1024)){setError("Use JPG, PNG ou WEBP de até 8 MB por imagem.");return}setFiles(next);setError("")}}/><Button type="button" variant="ghost" size="icon" disabled={!chat||busy} onClick={()=>input.current?.click()}><ImagePlus/></Button><textarea aria-label="Mensagem" placeholder="Diga ao Assistente o que fazer…" rows={2} ref={composer} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} className="max-h-32 min-w-0 flex-1 resize-none bg-transparent py-2 outline-none"/><Button type="submit" size="icon" disabled={!chat||busy||(!text.trim()&&!files.length)}>{busy?<Loader2 className="animate-spin"/>:<ArrowUp/>}</Button></form></div></footer>
  {attentionOpen&&<div className="fixed inset-0 z-[120] bg-black/30" onClick={()=>setAttentionOpen(false)}><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-background shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b px-4 py-4"><div><h2 className="font-bold">Precisa da sua atenção</h2><p className="text-xs text-muted-foreground">Revise os produtos. Nada será cadastrado antes de você salvar.</p></div><Button variant="ghost" size="icon" onClick={()=>setAttentionOpen(false)}><X/></Button></div><div className="min-h-0 flex-1 overflow-y-auto p-4 space-y-3">{pending.length===0?<p className="py-10 text-center text-sm text-muted-foreground">Nenhum produto aguardando sua ação.</p>:pending.map((p,i)=><PendingCard key={p.id} product={p} index={i} disabled={busy||resetting} edit={draftEdits[p.id]??{}} onChange={c=>updateDraft(p,c)}/>)}</div><div className="border-t p-4"><Button className="w-full" disabled={busy||ready.length===0} onClick={()=>void saveAll()}>Salvar cadastro {ready.length>0?`(${ready.length})`:""}</Button>{ready.length===0&&pending.length>0&&<p className="mt-2 text-center text-xs text-muted-foreground">Defina o preço de venda e corrija os itens pendentes antes de salvar.</p>}</div></aside></div>}
 </section>,document.body);
}

function PendingCard({product:p,index,disabled,edit,onChange}:{product:ChatProduct;index:number;disabled:boolean;edit:{name?:string;qty?:number;cost?:number;price?:number};onChange:(c:{name?:string;qty?:number;cost?:number;price?:number})=>void}){
 const name=edit.name??p.draft.name,qty=edit.qty??p.draft.qty,cost=edit.cost??p.draft.cost,price=edit.price??p.draft.manualPrice??"";
 const set=(key:"name"|"qty"|"cost"|"price",value:string)=>{if(key==="name")void onChange({name:value});else if(key==="qty")void onChange({qty:Number(value)});else if(key==="cost")void onChange({cost:Number(value.replace(",","."))});else void onChange({price:Number(value.replace(/\./g,"").replace(",","."))})};
 return <div className="rounded-xl border p-3"><div className="flex items-start gap-2"><span className="text-xs text-muted-foreground">{index+1}</span><div className="min-w-0 flex-1"><h3 className="font-semibold leading-snug">{name}</h3><p className="mt-1 text-xs text-muted-foreground">{p.status==="review"?p.error??"Precisa de conferência.":"Revise os dados e defina o preço. Nada será cadastrado ainda."}</p></div>{p.status==="review"&&<AlertTriangle className="size-4 shrink-0 text-amber-600"/>}</div><label className="mt-3 block text-sm">Nome<input value={name} disabled={disabled} onChange={e=>set("name",e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2"/></label><div className="mt-2 grid grid-cols-2 gap-2"><label className="text-sm">Quantidade<input inputMode="numeric" value={qty} disabled={disabled} onChange={e=>set("qty",e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2"/></label><label className="text-sm">Custo<input inputMode="decimal" value={String(cost).replace(".",",")} disabled={disabled} onChange={e=>set("cost",e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2"/></label></div><label className="mt-3 block text-sm font-medium">Preço de venda<input inputMode="decimal" value={price?String(price).replace(".",","):""} disabled={disabled} onChange={e=>set("price",e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2" placeholder="R$ 0,00"/></label></div>;
}
