/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SacolaRouteImport } from './routes/sacola'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MoedasRouteImport } from './routes/moedas'
import { Route as EuRouteImport } from './routes/eu'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ApiPublicSyncCatalogRouteImport } from './routes/api/public/sync-catalog'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicLoyverseReconcileRouteImport } from './routes/api/public/loyverse-reconcile'
import { Route as ApiPublicInfinitepayWebhookRouteImport } from './routes/api/public/infinitepay-webhook'
import { Route as ApiPublicExpireReservationsRouteImport } from './routes/api/public/expire-reservations'

const SacolaRoute = SacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MoedasRoute = MoedasRouteImport.update({
  id: '/moedas',
  path: '/moedas',
  getParentRoute: () => rootRouteImport,
} as any)
const EuRoute = EuRouteImport.update({
  id: '/eu',
  path: '/eu',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCatalogRoute = ApiPublicSyncCatalogRouteImport.update({
  id: '/api/public/sync-catalog',
  path: '/api/public/sync-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoyverseReconcileRoute =
  ApiPublicLoyverseReconcileRouteImport.update({
    id: '/api/public/loyverse-reconcile',
    path: '/api/public/loyverse-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInfinitepayWebhookRoute =
  ApiPublicInfinitepayWebhookRouteImport.update({
    id: '/api/public/infinitepay-webhook',
    path: '/api/public/infinitepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExpireReservationsRoute =
  ApiPublicExpireReservationsRouteImport.update({
    id: '/api/public/expire-reservations',
    path: '/api/public/expire-reservations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmar': typeof ConfirmarRoute
  '/cupons': typeof CuponsRoute
  '/eu': typeof EuRoute
  '/moedas': typeof MoedasRoute
  '/pedidos': typeof PedidosRoute
  '/sacola': typeof SacolaRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/expire-reservations': typeof ApiPublicExpireReservationsRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/api/public/loyverse-reconcile': typeof ApiPublicLoyverseReconcileRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmar': typeof ConfirmarRoute
  '/cupons': typeof CuponsRoute
  '/eu': typeof EuRoute
  '/moedas': typeof MoedasRoute
  '/pedidos': typeof PedidosRoute
  '/sacola': typeof SacolaRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/expire-reservations': typeof ApiPublicExpireReservationsRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/api/public/loyverse-reconcile': typeof ApiPublicLoyverseReconcileRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirmar': typeof ConfirmarRoute
  '/cupons': typeof CuponsRoute
  '/eu': typeof EuRoute
  '/moedas': typeof MoedasRoute
  '/pedidos': typeof PedidosRoute
  '/sacola': typeof SacolaRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/expire-reservations': typeof ApiPublicExpireReservationsRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/api/public/loyverse-reconcile': typeof ApiPublicLoyverseReconcileRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/sync-catalog': typeof ApiPublicSyncCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirmar'
    | '/cupons'
    | '/eu'
    | '/moedas'
    | '/pedidos'
    | '/sacola'
    | '/produto/$id'
    | '/api/public/expire-reservations'
    | '/api/public/infinitepay-webhook'
    | '/api/public/loyverse-reconcile'
    | '/api/public/manifest'
    | '/api/public/sync-catalog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/confirmar'
    | '/cupons'
    | '/eu'
    | '/moedas'
    | '/pedidos'
    | '/sacola'
    | '/produto/$id'
    | '/api/public/expire-reservations'
    | '/api/public/infinitepay-webhook'
    | '/api/public/loyverse-reconcile'
    | '/api/public/manifest'
    | '/api/public/sync-catalog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/confirmar'
    | '/cupons'
    | '/eu'
    | '/moedas'
    | '/pedidos'
    | '/sacola'
    | '/produto/$id'
    | '/api/public/expire-reservations'
    | '/api/public/infinitepay-webhook'
    | '/api/public/loyverse-reconcile'
    | '/api/public/manifest'
    | '/api/public/sync-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConfirmarRoute: typeof ConfirmarRoute
  CuponsRoute: typeof CuponsRoute
  EuRoute: typeof EuRoute
  MoedasRoute: typeof MoedasRoute
  PedidosRoute: typeof PedidosRoute
  SacolaRoute: typeof SacolaRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicExpireReservationsRoute: typeof ApiPublicExpireReservationsRoute
  ApiPublicInfinitepayWebhookRoute: typeof ApiPublicInfinitepayWebhookRoute
  ApiPublicLoyverseReconcileRoute: typeof ApiPublicLoyverseReconcileRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicSyncCatalogRoute: typeof ApiPublicSyncCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sacola': {
      id: '/sacola'
      path: '/sacola'
      fullPath: '/sacola'
      preLoaderRoute: typeof SacolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moedas': {
      id: '/moedas'
      path: '/moedas'
      fullPath: '/moedas'
      preLoaderRoute: typeof MoedasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eu': {
      id: '/eu'
      path: '/eu'
      fullPath: '/eu'
      preLoaderRoute: typeof EuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-catalog': {
      id: '/api/public/sync-catalog'
      path: '/api/public/sync-catalog'
      fullPath: '/api/public/sync-catalog'
      preLoaderRoute: typeof ApiPublicSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loyverse-reconcile': {
      id: '/api/public/loyverse-reconcile'
      path: '/api/public/loyverse-reconcile'
      fullPath: '/api/public/loyverse-reconcile'
      preLoaderRoute: typeof ApiPublicLoyverseReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infinitepay-webhook': {
      id: '/api/public/infinitepay-webhook'
      path: '/api/public/infinitepay-webhook'
      fullPath: '/api/public/infinitepay-webhook'
      preLoaderRoute: typeof ApiPublicInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-reservations': {
      id: '/api/public/expire-reservations'
      path: '/api/public/expire-reservations'
      fullPath: '/api/public/expire-reservations'
      preLoaderRoute: typeof ApiPublicExpireReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConfirmarRoute: ConfirmarRoute,
  CuponsRoute: CuponsRoute,
  EuRoute: EuRoute,
  MoedasRoute: MoedasRoute,
  PedidosRoute: PedidosRoute,
  SacolaRoute: SacolaRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicExpireReservationsRoute: ApiPublicExpireReservationsRoute,
  ApiPublicInfinitepayWebhookRoute: ApiPublicInfinitepayWebhookRoute,
  ApiPublicLoyverseReconcileRoute: ApiPublicLoyverseReconcileRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicSyncCatalogRoute: ApiPublicSyncCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
